export { Home as PageHome } from "./Home"
export { Personagens as PagePersonagens } from "./Personagens"
export { Sinopse as PageSinopse } from "./Sinopse"
export { default  as PageAdm} from "./Adm"
export { Cadastrar as PageCadastrar} from "./Cadastrar"
export { Login as PageLogin} from "./Login"